package com.awesome.park.util;

public enum BotState {
    START,
    WAKE_WAIT_FOR_NAME_AND_SURNAME,
    WAKE_WAIT_FOR_PHONE,
    WAKE_WAIT_FOR_BOOKING_TIME,
    SUP_BOARD_WAIT_FOR_NAME_AND_SURNAME, SUP_BOARD_WAIT_FOR_PHONE, SUP_BOARD_WAIT_FOR_SUP_BOOKING_TIME, SUP_BOARD_WAIT_FOR_CONFIRMATION, WAKE_WAIT_FOR_CONFIRMATION
}

